# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=5000)),
                ('image', models.ImageField(max_length=1024, upload_to=tasks.models.photo_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
