# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
