# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 20:36
from __future__ import unicode_literals

from django.db import migrations
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=tasks.models.JPEGImageField(upload_to=''),
        ),
    ]
